- id: askgov
  title: AskGov
  alias:
    - AskGov
  category: productivity
  image: https://file.go.gov.sg/askgovlogo.png
  sum: Q&A platform for members of the public
  link: https://products.open.gov.sg/askgov

- id: calsg
  title: CalSG
  alias:
    - CalSG
  category: productivity
  image: https://file.go.gov.sg/calsg-logo.png
  sum: Appointment bookings for Government
  link: https://products.open.gov.sg/calsg

- id: checkfirst
  title: CheckFirst
  alias:
    - CheckFirst
  category: productivity
  image: https://www.checkfirst.gov.sg/assets/logo.svg
  sum: Calculator and eligibility builder for the government
  link: https://products.open.gov.sg/checkfirst

- id: datagovsg
  title: Data.gov.sg
  alias:
    - Data.gov.sg
    - Data.gov
    - Data Gov
  category: productivity
  image: https://file.go.gov.sg/engagesg-logo.png
  sum: Streamline event attendance at government events.
  link: https://products.open.gov.sg/engagesg

- id: eventsg
  title: EventSG
  alias:
    - EventSG
    - EngageSG
  category: productivity
  image: https://file.go.gov.sg/engagesg-logo.png
  sum: Build government forms in minutes
  link: https://products.open.gov.sg/formsg

- id: formsg
  title: FormSG
  alias:
    - FormSG
  category: productivity
  image: https://file.go.gov.sg/formsg-logo-2.png
  sum: Build government forms in minutes
  link: https://products.open.gov.sg/formsg

- id: gogovsg
  title: GoGovSG
  alias:
    - GoGovSG
    - Go.gov.sg
    - go.gov.sg
    - Go.gov
  category: productivity
  image: https://file.go.gov.sg/gogovlogo.png
  sum: Create official government links in seconds
  link: https://products.open.gov.sg/gogovsg

- id: highway
  title: Highway
  alias:
    - Highway
    - highway
  category: productivity
  image: https://file.go.gov.sg/highway-logo.png
  sum: Secure file collection at scale through personalized links
  link: https://products.open.gov.sg/highway

- id: isomer
  title: Isomer
  alias:
    - Isomer
  category: productivity
  image: https://file.go.gov.sg/isomer-logo2.png
  sum: A static website building and hosting solution for the public service
  link: https://products.open.gov.sg/isomer

- id: lettersg
  title: LetterSG
  alias:
    - LetterSG
    - lettersg
    - letters
  category: productivity
  image: https://file.go.gov.sg/letters-logo.png
  sum: Easily create and track the issuance of personalized official e-letters to citizen
  link: https://products.open.gov.sg/lettersg

- id: pair
  title: Pair
  alias:
    - Pair
  category: productivity
  image: https://file.go.gov.sg/pair-logo.png
  sum: Large language model powered assistant for public officers
  link: https://products.open.gov.sg/pair

- id: plumber
  title: Plumber
  alias:
    - Plumber
  category: productivity
  image: https://file.go.gov.sg/plumber-logo.png
  sum: Workflow automation tool for everyday public officers
  link: https://products.open.gov.sg/plumber

- id: postman
  title: Postman
  alias:
    - Postman
  category: productivity
  image: https://file.go.gov.sg/postman-icon.png
  sum: An omnichannel communication tool for the Singapore Government
  link: https://products.open.gov.sg/postman

- id: scamshield
  title: ScamShield
  alias:
    - ScamShield
    - Scamshield
  category: anti-scam
  image: https://www.scamshield.org.sg/images/scamshield-favicon.png
  sum: Block unsolicited messages and calls
  link: https://products.open.gov.sg/scamshield

- id: sgid
  title: sgID
  alias:
    - sgID
    - SGID
  category: anti-scam
  image: https://file.go.gov.sg/sgid-key.png
  sum: Privacy-based authentication system
  link: https://products.open.gov.sg/sgid

- id: parkingsg
  title: ParkingSG
  alias:
    - Parking
    - ParkingSG
    - Parking.sg
    - Parking.SG
  category: payments
  image: https://file.go.gov.sg/parking-logo.png
  sum: Pay for parking using your mobile devices
  link:  https://products.open.gov.sg/parkingsg

- id: paysg
  title: PaySG
  alias:
    - PaySG
  category: payments
  image: https://pay.gov.sg/favicon.ico
  sum: Digitise payments for government agencies
  link: https://products.open.gov.sg/paysg

- id: redeem
  title: RedeemSG
  alias:
    - RedeemSG
    - Redeem
  category: payments
  image: https://file.go.gov.sg/redeemicon.png
  sum: Redemption tracking system to monitor the distribution of goods, tickets and vouchers in real time.
  link: https://products.open.gov.sg/redeem

- id: distributesg
  title: DistributeSG
  alias:
    - DistributeSG
  category: payments
  image: https://info.distribute.gov.sg/favicon.ico
  sum: Create and scale distribution campaigns to multiple locations quickly. Onboard staff easily to support your campaign with DistributeSG.
  link: https://products.open.gov.sg/distributesg

- id: has
  title: HAS
  alias:
    - HAS
    - Primary Care
    - HAS / Primary Care
  category: healthcare
  image: https://file.go.gov.sg/has-logo.png
  sum: Find and book vaccine appointments near you
  link:  https://products.open.gov.sg/has

- id: care360
  title: Care360
  alias:
    - Care360
  category: healthcare
  image: https://file.go.gov.sg/care360-logo.png
  sum: Patient management system for medical social workers.
  link: https://products.open.gov.sg/care360
